"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var renderCliField_js_1 = require("./renderCliField.js");
var renderCliTextField_js_1 = require("./renderCliTextField.js");
var renderCliBooleanField_js_1 = require("./renderCliBooleanField.js");
var renderCliNumberField_js_1 = require("./renderCliNumberField.js");
var renderCliSelectField_js_1 = require("./renderCliSelectField.js");
var renderCliStructureField_js_1 = require("./renderCliStructureField.js");
var renderCliLinkField_js_1 = require("./renderCliLinkField.js");
var renderCliImageField_js_1 = require("./renderCliImageField.js");
var renderCliHtmlField_js_1 = require("./renderCliHtmlField.js");
var renderCliMarkdownField_js_1 = require("./renderCliMarkdownField.js");
var renderCliColorField_js_1 = require("./renderCliColorField.js");
var renderCliListField_js_1 = require("./renderCliListField.js");
var renderCliObjectField_js_1 = require("./renderCliObjectField.js");
var renderCliRichtextField_js_1 = require("./renderCliRichtextField.js");
(0, renderCliField_js_1.registerCliFieldRenderer)('core/text', renderCliTextField_js_1.renderCliTextField);
(0, renderCliField_js_1.registerCliFieldRenderer)('core/boolean', renderCliBooleanField_js_1.renderCliBooleanField);
(0, renderCliField_js_1.registerCliFieldRenderer)('core/number', renderCliNumberField_js_1.renderCliNumberField);
(0, renderCliField_js_1.registerCliFieldRenderer)('core/select', renderCliSelectField_js_1.renderCliSelectField);
(0, renderCliField_js_1.registerCliFieldRenderer)('core/structure', renderCliStructureField_js_1.renderCliStructureField);
(0, renderCliField_js_1.registerCliFieldRenderer)('core/link', renderCliLinkField_js_1.renderCliLinkField);
(0, renderCliField_js_1.registerCliFieldRenderer)('core/image', renderCliImageField_js_1.renderCliImageField);
(0, renderCliField_js_1.registerCliFieldRenderer)('core/html', renderCliHtmlField_js_1.renderCliHtmlField);
(0, renderCliField_js_1.registerCliFieldRenderer)('core/markdown', renderCliMarkdownField_js_1.renderCliMarkdownField);
(0, renderCliField_js_1.registerCliFieldRenderer)('core/color', renderCliColorField_js_1.renderCliColorField);
(0, renderCliField_js_1.registerCliFieldRenderer)('core/list', renderCliListField_js_1.renderCliListField);
(0, renderCliField_js_1.registerCliFieldRenderer)('core/object', renderCliObjectField_js_1.renderCliObjectField);
(0, renderCliField_js_1.registerCliFieldRenderer)('core/rich-text', renderCliRichtextField_js_1.renderCliRichtextField);
